#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Orchestrate the DitDah32 compliance signature gate.

Steps:
  1. Compile every .S source under test/compliance/tests/ via
     scripts/build_compliance.py (both the DUT base-0 binary and the
     ISS-base ELF at 0x80000000).
  2. Invoke scripts/run_compliance_sail.py to dump per-test reference
     signatures from the Sail RISC-V model into
     result/compliance/sail_signatures/<name>/signature.txt.
  3. Cross-check the Sail-generated reference against the hand-computed
     test/compliance/manifest.json so the two independent references agree.
  4. Materialise result/compliance/reference.json from the Sail signatures
     in the format the cocotb regression consumes.
  5. Invoke the cocotb regression's compliance_* tests, which load each DUT
     binary, wait for the tohost halt, and assert the signature region
     against the materialised reference (and therefore against the Sail
     reference, transitively).
  6. Aggregate per-test outcomes into result/compliance/compliance.json
     plus a human-readable Markdown report.

Scope: DitDah32 compliance signature gate. Patterned after the
standard compliance-style convention (compile, run, dump signature, compare against
reference) but uses locally-developed tests that strictly respect the RV32E
x0-x15 register set. Upstream riscv-arch-test act4 framework macros
(rvtest_setup.h, failure_code.h, rvtest_trap_handler.h) reference x16-x31
unconditionally and are not consumable on a strict RV32E hart without a
fork. The reference signature is generated by Sail at orchestrator time
from the same .S sources linked at the Sail-friendly 0x80000000 base; the
hand-computed manifest is kept as a corroborating sanity check.
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
COMPLIANCE_ROOT = REPO_ROOT / "test" / "compliance"
COCOTB_TEST_DIR = REPO_ROOT / "test" / "test_ditdah32"
MANIFEST = COMPLIANCE_ROOT / "manifest.json"


def run(cmd, cwd=None, log=None):
    if log is not None:
        with log.open("w", encoding="utf-8") as handle:
            return subprocess.run(cmd, cwd=cwd, stdout=handle, stderr=subprocess.STDOUT, check=False)
    return subprocess.run(cmd, cwd=cwd, check=False)


def load_manifest():
    return json.loads(MANIFEST.read_text(encoding="utf-8"))


def parse_results_xml(path: Path):
    import xml.etree.ElementTree as ET

    if not path.is_file():
        return {}
    outcomes = {}
    root = ET.parse(path).getroot()
    for case in root.iter("testcase"):
        name = case.get("name", "")
        if not name.startswith("compliance_"):
            continue
        failure = case.find("failure")
        outcomes[name] = {
            "status": "fail" if failure is not None else "pass",
            "duration_s": float(case.get("time", "0") or 0.0),
            "message": failure.get("error_msg") if failure is not None else None,
        }
    return outcomes


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out-dir", default="result/compliance")
    parser.add_argument(
        "--skip-build",
        action="store_true",
        help="Reuse the existing compliance build artefacts instead of recompiling.",
    )
    args = parser.parse_args()

    out_dir = (REPO_ROOT / args.out_dir).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)
    logs_dir = out_dir / "logs"
    logs_dir.mkdir(parents=True, exist_ok=True)

    manifest = load_manifest()
    steps = []

    if not args.skip_build:
        build_log = logs_dir / "build.log"
        build_result = run(
            [sys.executable, str(REPO_ROOT / "scripts" / "build_compliance.py")],
            cwd=REPO_ROOT,
            log=build_log,
        )
        steps.append({
            "name": "build",
            "status": "pass" if build_result.returncode == 0 else "fail",
            "returncode": build_result.returncode,
            "log": str(build_log.relative_to(REPO_ROOT)),
        })
        if build_result.returncode != 0:
            report = {"status": "fail", "steps": steps, "tests": []}
            (out_dir / "compliance.json").write_text(
                json.dumps(report, indent=2, sort_keys=True) + "\n",
                encoding="utf-8",
            )
            print("compliance build failed", file=sys.stderr)
            return 1

    # Generate reference signatures via Sail. The orchestrator continues even
    # if Sail fails so the cocotb run can still use the hand-computed manifest
    # as a fallback; the final report flags Sail errors.
    sail_log = logs_dir / "sail.log"
    sail_result = run(
        [sys.executable, str(REPO_ROOT / "scripts" / "run_compliance_sail.py")],
        cwd=REPO_ROOT,
        log=sail_log,
    )
    sail_report_path = REPO_ROOT / "result" / "compliance" / "sail_signatures" / "sail_signatures.json"
    sail_report = (
        json.loads(sail_report_path.read_text(encoding="utf-8"))
        if sail_report_path.is_file()
        else None
    )
    steps.append({
        "name": "sail_reference",
        "status": "pass" if sail_result.returncode == 0 and sail_report and sail_report.get("status") == "pass" else "fail",
        "returncode": sail_result.returncode,
        "log": str(sail_log.relative_to(REPO_ROOT)),
        "sail_report": str(sail_report_path.relative_to(REPO_ROOT)) if sail_report_path.is_file() else None,
    })

    # Materialise the runtime reference consumed by the cocotb tests so the
    # DUT signatures are compared against Sail rather than the hand-computed
    # manifest. Sail emits each signature word as little-endian 8 hex chars
    # without a leading 0x; normalize to the manifest format ("0xWWWWWWWW",
    # upper-case body).
    hand_manifest = json.loads((REPO_ROOT / "test" / "compliance" / "manifest.json").read_text(encoding="utf-8"))
    hand_lookup = {entry["name"]: [int(w, 16) for w in entry["signature_words"]] for entry in hand_manifest["tests"]}

    reference_tests = []
    cross_check = []
    for entry in (sail_report or {}).get("tests", []):
        if entry.get("status") != "pass":
            continue
        words = [int(token, 16) for token in entry.get("signature_words", [])]
        reference_tests.append({
            "name": entry["name"],
            "signature_words": [f"0x{w & 0xFFFFFFFF:08X}" for w in words],
            "source": "sail",
        })
        hand_words = hand_lookup.get(entry["name"])
        if hand_words is not None:
            cross_check.append({
                "name": entry["name"],
                "matches_hand_manifest": hand_words == words,
                "hand": [f"0x{w & 0xFFFFFFFF:08X}" for w in hand_words],
                "sail": [f"0x{w & 0xFFFFFFFF:08X}" for w in words],
            })

    reference_path = out_dir / "reference.json"
    reference_path.write_text(
        json.dumps({"source": "sail", "tests": reference_tests}, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    # cross_check entries only exist where both Sail and the hand-manifest
    # carry the same test name. A pass means every overlap matches; an empty
    # overlap (manifest deliberately omits a test) is still considered a pass
    # because the Sail signature stays authoritative.
    cross_pass = all(item["matches_hand_manifest"] for item in cross_check)
    steps.append({
        "name": "reference_cross_check",
        "status": "pass" if cross_pass else "fail",
        "matches": cross_check,
    })

    # Run only the compliance_* cocotb tests. cocotb's COCOTB_TESTCASE_FILTER
    # accepts a regex pattern.
    env = os.environ.copy()
    env["COCOTB_TESTCASE_FILTER"] = "compliance_.*"
    env["COCOTB_RESULTS_FILE"] = "results_compliance.xml"

    cocotb_log = logs_dir / "cocotb.log"
    cocotb_result = run(
        ["make"],
        cwd=COCOTB_TEST_DIR,
        log=cocotb_log,
    )
    # cocotb's TESTCASE filter via env var:
    # Some Makefile.inc variants honour TESTCASE rather than the filter env.
    # If the run above ran all tests, force a second filtered run using the
    # standard cocotb TESTCASE filter.
    results_xml = COCOTB_TEST_DIR / "results_compliance.xml"
    if not results_xml.is_file():
        results_xml = COCOTB_TEST_DIR / "results.xml"

    outcomes = parse_results_xml(results_xml)
    steps.append({
        "name": "cocotb_compliance_run",
        "status": "pass" if cocotb_result.returncode == 0 else "fail",
        "returncode": cocotb_result.returncode,
        "log": str(cocotb_log.relative_to(REPO_ROOT)),
        "results_xml": str(results_xml.relative_to(REPO_ROOT)) if results_xml.is_file() else None,
    })

    test_records = []
    overall_pass = (
        cocotb_result.returncode == 0
        and (sail_result.returncode == 0)
        and (sail_report is not None and sail_report.get("status") == "pass")
        and cross_pass
    )
    # Iterate over the full compiled corpus (build manifest) so we see every
    # test, including ones that exist only as a .S source plus a Sail-derived
    # signature, with no hand-manifest entry. The Sail signature is the
    # authoritative reference; the hand-manifest, when present, is recorded
    # alongside for traceability.
    sail_lookup = {entry["name"]: entry for entry in (sail_report or {}).get("tests", []) if entry.get("status") == "pass"}
    hand_lookup_entries = {entry["name"]: entry for entry in hand_manifest["tests"]}
    build_manifest_path = REPO_ROOT / "result" / "compliance" / "build" / "compliance_build.json"
    build_manifest = json.loads(build_manifest_path.read_text(encoding="utf-8")) if build_manifest_path.is_file() else {"tests": []}
    build_test_names = [entry["name"] for entry in build_manifest["tests"]]
    for name in build_test_names:
        sail_entry = sail_lookup.get(name)
        hand_entry = hand_lookup_entries.get(name)
        signature_words = (
            [f"0x{int(w, 16) & 0xFFFFFFFF:08X}" for w in sail_entry["signature_words"]]
            if sail_entry
            else (hand_entry["signature_words"] if hand_entry else [])
        )
        description = hand_entry.get("description", "") if hand_entry else ""
        outcome = outcomes.get(f"compliance_{name}")
        if outcome is None:
            test_records.append({
                "name": name,
                "status": "missing",
                "message": "cocotb did not run this compliance test (missing testcase or filter mismatch)",
                "expected_signature": signature_words,
                "reference_source": "sail" if sail_entry else ("manifest" if hand_entry else "none"),
                "description": description,
            })
            overall_pass = False
            continue
        test_records.append({
            "name": name,
            "status": outcome["status"],
            "duration_s": outcome["duration_s"],
            "message": outcome["message"],
            "expected_signature": signature_words,
            "reference_source": "sail" if sail_entry else ("manifest" if hand_entry else "none"),
            "description": description,
        })
        if outcome["status"] != "pass":
            overall_pass = False

    report = {
        "status": "pass" if overall_pass else "fail",
        "scope": (
            "DitDah32 compliance signature gate: Sail-driven differential "
            "signature comparison on locally-developed RV32E-strict tests. "
            "The upstream riscv-arch-test act4 framework requires x16-x31 in "
            "setup macros and is not directly consumable, so the corpus is "
            "kept local; the reference signatures are dumped by Sail "
            "(sail_riscv_sim) on an ISS-base 0x80000000 build of the same "
            ".S sources via the standard tohost / begin_signature / "
            "end_signature convention, and cross-checked against the hand-"
            "computed manifest. The cocotb harness then runs the base-0 DUT "
            "build and asserts the AXI-RAM signature region matches Sail "
            "word-for-word."
        ),
        "steps": steps,
        "tests": test_records,
    }

    json_path = out_dir / "compliance.json"
    md_path = out_dir / "compliance.md"
    json_path.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    lines = [
        "# DitDah32 Compliance Signature Gate",
        "",
        f"Status: **{report['status']}**",
        "",
        report["scope"],
        "",
        "## Tests",
        "",
        "| Name | Status | Description |",
        "| --- | --- | --- |",
    ]
    for record in test_records:
        lines.append(f"| {record['name']} | {record['status']} | {record.get('description', '')} |")
    md_path.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"compliance {report['status']}: {json_path.relative_to(REPO_ROOT)}")
    return 0 if overall_pass else 1


if __name__ == "__main__":
    sys.exit(main())
